### ISSUE TITLE
Gazetteer review - 1

### ISSUE THREAD

**Issue by itcareerswitch** [an-obtuse-snowball/project1#2]
Pre-loader.
map.fitBounds().
Look at recommended Leaflet plugins.
Fit map exactly to all device sizes.
Use Bootstrap tables in modals for better presentation.
Use more inventive styling for weather and include forecast for next few days.
Use select tag for countries and use jQuery to change value after navigator returns country code:
$('#countrySelect').val(countryCode).change();
Look at Leaflet layers control.

**Comment by an-obtuse-snowball** [comment]
Issues resolved as of latest merge 
#7
